apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: seccomp-profile-installer
commonLabels:
  app: seccomp-profile-installer
resources:
- ../../cluster-scope/base/apps/daemonset
- ../../cluster-scope/base/core/persistentvolumeclaims
- ../../cluster-scope/base/core/serviceaccounts
- ../../cluster-scope/base/rbac.authorization.k8s.io


configMapGenerator:
  - name: seccomp-profiles
    files:
      - allow-personality.json
